"use client";

import { useState, useEffect, useRef, Suspense } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FieldGroup, Field, FieldLabel } from "@/components/ui/field";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Loader2,
  Sparkles,
  Check,
  Copy,
  ArrowRight,
  LineChart,
  Flame,
} from "lucide-react";
import { toast } from "sonner";
import { GoogleGenAI } from "@/lib/gemini-sdk";

interface GeneratedConcept {
  id: string;
  title: string;
  description: string;
  trigger: string;
  structure: string;
}

function IdeasContent() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const audienceParam = searchParams.get("audience");
  const goalParam = searchParams.get("goal");

  const [niche, setNiche] = useState("Software Engineering");
  const [audience, setAudience] = useState(() => {
    const param = searchParams.get("audience");
    return param ? decodeURIComponent(param) : "Beginners";
  });
  const [goal, setGoal] = useState(() => {
    const param = searchParams.get("goal");
    return param ? decodeURIComponent(param) : "Maximize Engagement";
  });
  const [isLoading, setIsLoading] = useState(false);
  const [concepts, setConcepts] = useState<GeneratedConcept[] | null>(null);
  
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [pushedId, setPushedId] = useState<string | null>(null);
  const hasAutoGeneratedRef = useRef(false);

  const handleGenerate = async (optNiche?: string, optAudience?: string, optGoal?: string) => {
    setIsLoading(true);
    setConcepts(null);

    const targetNiche = optNiche || niche;
    const targetAudience = optAudience || audience;
    const targetGoal = optGoal || goal;

    try {
      const ai = new GoogleGenAI({ apiKey: "virtual-key" });
      const model = ai.getGenerativeModel({ model: "gemini-2.0-flash" });
      const prompt = `Generate ideas for niche: ${targetNiche}, audience: ${targetAudience}, goal: ${targetGoal}`;
      
      const response = await model.generateContent(prompt);
      const data = JSON.parse(response.response.text());
      
      setConcepts(data.concepts);
      toast.success("Generated 5 new concepts!");
    } catch {
      toast.error("Failed to generate ideas.");
    } finally {
      setIsLoading(false);
    }
  };

  // Auto-generate on mount if search params are provided (runs once)
  useEffect(() => {
    if (hasAutoGeneratedRef.current) return;
    if (!audienceParam && !goalParam) return;

    hasAutoGeneratedRef.current = true;

    // Defer outside the synchronous effect body to avoid cascading-render lint warning
    const timer = setTimeout(() => {
      const targetAudience = audienceParam ? decodeURIComponent(audienceParam) : audience;
      const targetGoal = goalParam ? decodeURIComponent(goalParam) : goal;
      handleGenerate(niche, targetAudience, targetGoal);
    }, 0);

    return () => clearTimeout(timer);
  // Only run on mount — audience/goal/niche are already initialised from params via lazy useState
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    toast.success("Concept title copied!");
    setTimeout(() => setCopiedId(null), 2000);
  };

  const pushToContentOS = (concept: GeneratedConcept) => {
    try {
      const stored = localStorage.getItem("pulse_kanban_cards");
      const currentCards = stored ? JSON.parse(stored) : [];
      
      const newCard = {
        id: `card-${Date.now()}-${concept.id}`,
        title: concept.title,
        niche: niche,
        status: "Ideas"
      };
      
      localStorage.setItem("pulse_kanban_cards", JSON.stringify([...currentCards, newCard]));
      setPushedId(concept.id);
      toast.success("Concept added to Content OS Ideas!");
      setTimeout(() => setPushedId(null), 2000);
    } catch {
      toast.error("Failed to add concept to Content OS");
    }
  };

  const refineHook = (title: string) => {
    const encoded = encodeURIComponent(title);
    router.push(`/dashboard/hooks?hookText=${encoded}`);
  };

  const analyzeDraft = (title: string) => {
    const encoded = encodeURIComponent(title);
    router.push(`/dashboard/analyzer?draft=${encoded}`);
  };

  return (
    <div className="flex flex-col gap-6">
      {/* Title */}
      <div className="flex flex-col gap-1.5">
        <h2 className="text-2xl font-bold tracking-tight text-foreground">Idea Engine</h2>
        <p className="text-sm text-muted-foreground">
          Generate tailor-made content ideas and angles based on your audience parameters and niche.
        </p>
      </div>

      {/* Selectors using FieldGroup and Field with Shadcn Select */}
      <FieldGroup className="grid gap-4 md:grid-cols-3">
        <Card className="border border-border bg-card p-5 flex flex-col justify-center">
          <Field className="flex flex-col gap-1.5">
            <FieldLabel htmlFor="niche-select" className="font-bold text-foreground text-xs uppercase tracking-wider">
              1. Select Niche
            </FieldLabel>
            <Select value={niche} onValueChange={setNiche}>
              <SelectTrigger id="niche-select" className="w-full h-10 bg-background border border-input rounded-xl px-3 text-left">
                <SelectValue placeholder="Select Niche" />
              </SelectTrigger>
              <SelectContent position="popper" className="w-full bg-popover text-popover-foreground">
                <SelectItem value="Software Engineering">Software Engineering</SelectItem>
                <SelectItem value="Design & UIUX">Design & UIUX</SelectItem>
                <SelectItem value="Marketing & Growth">Marketing & Growth</SelectItem>
                <SelectItem value="Cryptocurrency & Web3">Cryptocurrency & Web3</SelectItem>
              </SelectContent>
            </Select>
          </Field>
        </Card>

        <Card className="border border-border bg-card p-5 flex flex-col justify-center">
          <Field className="flex flex-col gap-1.5">
            <FieldLabel htmlFor="audience-select" className="font-bold text-foreground text-xs uppercase tracking-wider">
              2. Target Audience
            </FieldLabel>
            <Select value={audience} onValueChange={setAudience}>
              <SelectTrigger id="audience-select" className="w-full h-10 bg-background border border-input rounded-xl px-3 text-left">
                <SelectValue placeholder="Select Audience" />
              </SelectTrigger>
              <SelectContent position="popper" className="w-full bg-popover text-popover-foreground">
                <SelectItem value="Beginners">Beginners</SelectItem>
                <SelectItem value="Intermediate Creators">Intermediate Creators</SelectItem>
                <SelectItem value="Founders / Operators">Founders / Operators</SelectItem>
                <SelectItem value="General Public">General Public</SelectItem>
              </SelectContent>
            </Select>
          </Field>
        </Card>

        <Card className="border border-border bg-card p-5 flex flex-col justify-center">
          <Field className="flex flex-col gap-1.5">
            <FieldLabel htmlFor="goal-select" className="font-bold text-foreground text-xs uppercase tracking-wider">
              3. Core Goal
            </FieldLabel>
            <Select value={goal} onValueChange={setGoal}>
              <SelectTrigger id="goal-select" className="w-full h-10 bg-background border border-input rounded-xl px-3 text-left">
                <SelectValue placeholder="Select Goal" />
              </SelectTrigger>
              <SelectContent position="popper" className="w-full bg-popover text-popover-foreground">
                <SelectItem value="Maximize Engagement">Maximize Engagement</SelectItem>
                <SelectItem value="Educational Value">Educational Value</SelectItem>
                <SelectItem value="Lead Generation">Lead Generation</SelectItem>
                <SelectItem value="Contrarian Debate">Contrarian Debate</SelectItem>
              </SelectContent>
            </Select>
          </Field>
        </Card>
      </FieldGroup>

      {/* Results Box */}
      <Card className="border border-border bg-card min-h-[220px] flex flex-col justify-between">
        <CardHeader>
          <CardTitle className="text-base font-bold">Concepts Pipeline</CardTitle>
          <CardDescription>Tailored ideas generated based on your settings above.</CardDescription>
        </CardHeader>
        <CardContent className="flex-1 flex flex-col justify-between gap-6 pb-6">
          {concepts ? (
            <div className="flex flex-col gap-4 w-full">
              {concepts.map((concept) => (
                <div
                  key={concept.id}
                  className="flex flex-col gap-3.5 p-4 rounded-xl bg-muted/40 border border-border"
                >
                  <div className="space-y-1.5">
                    <div className="flex flex-wrap items-center gap-2">
                      <Badge className="bg-emerald-500/10 text-emerald-500 border border-emerald-500/20 hover:bg-emerald-500/10 text-[9px] py-0 px-2">
                        {niche}
                      </Badge>
                      <Badge variant="outline" className="text-[9px] py-0 px-2 border-primary/20 text-primary">
                        Trigger: {concept.trigger}
                      </Badge>
                    </div>
                    <p className="text-sm font-semibold text-foreground leading-relaxed">
                      {concept.title}
                    </p>
                    <p className="text-xs text-muted-foreground leading-relaxed">
                      {concept.description}
                    </p>
                    <p className="text-[11px] font-mono text-muted-foreground bg-background p-2 rounded border border-border mt-2">
                      <strong>Blueprint:</strong> {concept.structure}
                    </p>
                  </div>
                  <div className="flex flex-wrap items-center justify-end gap-2 border-t border-border/50 pt-3">
                    <Button
                      size="sm"
                      variant="ghost"
                      onClick={() => copyToClipboard(concept.title, concept.id)}
                      className="active-scale text-xs gap-1.5 h-8 px-2.5"
                    >
                      {copiedId === concept.id ? (
                        <>
                          <Check className="size-3 text-emerald-500" />
                          <span>Copied</span>
                        </>
                      ) : (
                        <>
                          <Copy className="size-3" />
                          <span>Copy Hook</span>
                        </>
                      )}
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => refineHook(concept.title)}
                      className="active-scale text-xs gap-1.5 h-8 px-2.5"
                    >
                      <Flame className="size-3 text-amber-500" />
                      <span>Refine Hook</span>
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => analyzeDraft(concept.title)}
                      className="active-scale text-xs gap-1.5 h-8 px-2.5"
                    >
                      <LineChart className="size-3 text-muted-foreground" />
                      <span>Analyze Draft</span>
                    </Button>
                    <Button
                      size="sm"
                      onClick={() => pushToContentOS(concept)}
                      className="active-scale text-xs gap-1.5 h-8 px-2.5"
                    >
                      {pushedId === concept.id ? (
                        <>
                          <Check className="size-3 text-emerald-500" />
                          <span>Added!</span>
                        </>
                      ) : (
                        <>
                          <ArrowRight className="size-3" />
                          <span>Send to OS</span>
                        </>
                      )}
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center text-center p-6 gap-2">
              <p className="text-sm text-muted-foreground">
                Configure parameters above and click below to generate personalized concepts.
              </p>
              <Button
                onClick={() => handleGenerate()}
                disabled={isLoading}
                className="active-scale h-10 px-8 mt-2 font-semibold rounded-xl"
              >
                {isLoading ? (
                  <>
                    <Loader2 className="animate-spin size-4" />
                    Generating concepts...
                  </>
                ) : (
                  <>
                    <Sparkles className="size-4" />
                    Generate Concepts
                  </>
                )}
              </Button>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

export default function Page() {
  return (
    <Suspense fallback={
      <div className="flex flex-col gap-6">
        <div className="flex flex-col gap-1.5">
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Idea Engine</h2>
          <p className="text-sm text-muted-foreground">Generate tailor-made content ideas.</p>
        </div>
        <div className="flex-1 flex items-center justify-center min-h-[400px] text-xs text-muted-foreground">
          <Loader2 className="animate-spin size-6 text-primary mr-2" />
          Loading engine...
        </div>
      </div>
    }>
      <IdeasContent />
    </Suspense>
  );
}
